# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "打包上传APPStore"
  lane :dis do

    # 自动代码签名
    #enable_automatic_code_signing
    increment_build_number(xcodeproj: "HiWallet.xcodeproj")

    build_app(
		workspace: "HiWallet.xcworkspace", 
		scheme: "HiWallet_Dis",
		clean: true, 			# 在打包前是否先执行clean。
		configuration: "Release",       #环境
		output_directory: "./build",
        	output_name: "HiWallet_Release",

		export_options: {
  			 method: "app-store",
  			 thinning: "<none>"
			}
	
	     )

    upload_to_app_store(skip_metadata: true, skip_screenshots: true)

  end

  desc "上传fir.im"
  lane :test do
	
	increment_build_number(xcodeproj: "HiWallet.xcodeproj")

	build_app(

		workspace: "HiWallet.xcworkspace",
 		scheme: "HiWallet_Dev",
  		configuration: "Debug", 	#编译模式，默认release
		include_bitcode: false, 	#不包括会减小包大小
  		silent: true,  			#隐藏构建时候不需要所有信息
		include_symbols: false,
		output_directory: "./build",
        	output_name: "HiWallet_Test",
		clean: true, 			# 在打包前是否先执行clean。
 		export_options: {
  			 method: "ad-hoc",
  			 thinning: "<none>"
			}
		)

	firim(firim_api_token: "1c89428c199b245fec43f8329846b15f")
  end


  desc "上传fir.im"
  lane :testDev do
	
	increment_build_number(xcodeproj: "HiWallet.xcodeproj")

	build_app(

		workspace: "HiWallet.xcworkspace",
 		scheme: "HiWallet_Dev",
  		configuration: "Debug", 	#编译模式，默认release
		include_bitcode: false, 	#不包括会减小包大小
  		silent: true,  			#隐藏构建时候不需要所有信息
		include_symbols: false,
		output_directory: "./build",
        	output_name: "HiWallet_Test",
		clean: true, 			# 在打包前是否先执行clean。
 		export_options: {
  			 method: "development",
  			 thinning: "<none>"
			}
		)

	firim(firim_api_token: "1c89428c199b245fec43f8329846b15f")
  end

end
