use_frameworks!

platform :ios, '9.0'

target 'NaptimeFileProtocol_Example' do

    pod 'NaptimeFileProtocol', :path => '../'

    target 'NaptimeFileProtocol_Tests' do
        inherit! :search_paths

        pod 'Quick', :git => "https://github.com/Quick/Quick.git", :branch => "master"
        pod 'Nimble', :git => "https://github.com/Quick/Nimble.git", :branch => "master"
    end
end
